name: dtn
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.6
  - pip
  # BASICS
  - numpy
  - scipy
  - pandas
  - tqdm
  - ipython
  # VISUALIZATION
  - matplotlib
  - seaborn
  - bokeh
  # ML, STATS & DEEP LEARNING
  - statsmodels
  - scikit-learn
  - xgboost
  - pytorch
  - shap
  - pip:
     - -e .  # install git checkout of datathon2022 in editable mode
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
     - jax
     - streamlit
     - flask
     - celery
     - redis
     - py-spy
     - h5py
     - hdfdict
     - scikit-garden

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pre_commit
  - nbdime
  - nbstripout
